### ISSUE TITLE
Responsive web app

### ISSUE THREAD

**Issue by surajcool203** [technojam/world-clock#4]
our web app is not responsive,so u have to make it responsive for phones,

**Comment by dennypradipta** [comment]
I want to do this :)

**Comment by surajcool203** [comment]
okk you can work on it by today

**Comment by Aakash-Kumar-Sharma** [comment]
I want to do this

**Comment by iswarya-c** [comment]
I would like to work on this!

**Comment by surajcool203** [comment]
okk i will assign this to all of you

**Comment by surajcool203** [comment]
i have assigned all of you
