### ISSUE TITLE
Dropdown Box

### ISSUE THREAD

**Issue by surajcool203** [technojam/world-clock#48]
scroll option in the dropdown pannel for viewing countries.

**Comment by ashvinimore** [comment]
Hi Suraj,
Can you assign me that task?
Thank You

**Comment by surajcool203** [comment]
okk go a head

**Comment by ashvinimore** [comment]
Ok. Thanks

**Comment by ashvinimore** [comment]
Hello Suraj,
I have added scrollbar by slightly changing index.html and main.js. Please review the code
Thank You
